apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: argo-workflow
rules:
- apiGroups: 
  - argoproj.io
  resources:
    - workflowtaskresults
  verbs:
    - create
    - patch
    - update
