apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: hello-template
  namespace: argo

spec:
  serviceAccountName: argo-workflow

  entrypoint: main

  arguments:
    parameters:
      - name: message
        value: Hello from default parameter

  templates:
    - name: main
      inputs:
        parameters:
          - name: message

      container:
        image: alpine:3.20
        command:
          - sh
          - -c
        args:
          - echo "{{inputs.parameters.message}}"
